version: "0.1"
global:
  setup:
    - pnpm install
pipeline:
  runTest:
    exec:
      - npx vitest run {{testFilePath}}
settings:
  codeModels: ["gpt-4o"]
  skipFailedTests: false
  exportFunctionOrClass: allow
  testPlacementStrategies:
    - type: co-located
      testFilePattern: "{{sourceFileName}}.spec.ts"